version: '2.3'

services:
  db:
    image: mysql/mysql-server
    container_name: mysql01
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306
# networks:
#   - net_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abcd1234
    volumes:
      - /docker/mysql/mysql-init:/docker-entrypoint-initdb.d
      - /docker/mysql/data:/var/lib/mysql
# volumes:
#   mysql-data:
#     external: true
# networks:
#   net_mysql:
#     external: true